DROP TABLE IF EXISTS EXECUTION_SCHEMA
GO
CREATE TABLE EXECUTION_SCHEMA (
	EXECUTION_ID INT NOT NULL IDENTITY(1,1),
	EXECUTION_COUNT INT NOT NULL,
	STOREDPROCEDURE_ID INT NOT NULL,
	CORRESPONDING_EXECUTION_ID INT NULL,
	PARAMETER NVARCHAR(MAX) NULL,
	PRIMARY KEY (EXECUTION_ID)
);
GO